name: Terraform

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      CLOUDFLARE_BASE64ENCODEDPEMFILE:
        required: false
      CLOUDFLARE_BASE64ENCODEDCONFIGJSONFILE:
        required: false
      CLOUDFLARE_TUNEL_ID:
        required: false

    inputs:
      deploy:
        description: Faz deploy da aplicacao
        type: boolean
        default: false
      environment:
        description: Nome do environment do GitHub a ser usado no deploy
        type: string

jobs:
  plan:
    runs-on: eich
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: eich-template-actions/template-action-sast/.github/actions/sast@master
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}

      - name: Init
        run: terraform init

      - name: Plan
        env:
          TF_VAR_cloudflare_base64EncodedPemFile: ${{ secrets.CLOUDFLARE_BASE64ENCODEDPEMFILE }}
          TF_VAR_cloudflare_base64EncodedConfigJsonFile: ${{ secrets.CLOUDFLARE_BASE64ENCODEDCONFIGJSONFILE }}
          TF_VAR_cloudflare_tunel_id: ${{ secrets.CLOUDFLARE_TUNEL_ID }}
        run: terraform plan -out=tfplan

      - name: Upload do plano como artefato
        if: ${{ inputs.deploy }}
        uses: actions/upload-artifact@v4
        with:
          name: plano-binario
          path: tfplan
          retention-days: 0

  apply:
    runs-on: eich
    environment: ${{ inputs.environment }}
    needs: plan
    if: ${{ inputs.deploy }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init
        run: terraform init
      - name: Download do plano do artefato
        uses: actions/download-artifact@v4
        with:
          name: plano-binario
      - name: Apply
        env:
          TF_VAR_cloudflare_base64EncodedPemFile: ${{ secrets.CLOUDFLARE_BASE64ENCODEDPEMFILE }}
          TF_VAR_cloudflare_base64EncodedConfigJsonFile: ${{ secrets.CLOUDFLARE_BASE64ENCODEDCONFIGJSONFILE }}
          TF_VAR_cloudflare_tunel_id: ${{ secrets.CLOUDFLARE_TUNEL_ID }}
        run: terraform apply -auto-approve tfplan

      - name: Resultado
        run: |
          echo "Terraform aplicado no ambiente: ${{ inputs.environment }} - Ambiente: $AMBIENTE"
        env:
          AMBIENTE: ${{ vars.AMBIENTE }}

  limpeza:
    if: always()
    needs: apply
    runs-on: eich
    steps:
      - name: Limpar
        uses: eich-template-actions/template-action-limpeza/actions/limpeza@master
